[pytest]
#addopts = --html=report.html --self-contained-html
addopts = --tb=short

markers =
    smoke: fast, critical path tests that verify core functionality
    regression: full suite tests that verify nothing is broken